import type { Metadata } from "next";
import { Manrope, Rock_Salt, IBM_Plex_Mono } from "next/font/google";
import "./globals.scss";
import { CSSProperties } from "react";
import Header from "./components/header/Header";
import Script from "next/script";
import Footer from "./components/footer/Footer";
const m = Manrope({
  subsets: ["latin"],
});

const rs = Rock_Salt({
  weight: "400",
  subsets: ["latin"],
});

const stroke = IBM_Plex_Mono({
  weight: "700",
});

export const metadata: Metadata = {
  title: "Vartix ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`body`}
        style={
          {
            "--fontm": m.style.fontFamily,
            "--fontrs": rs.style.fontFamily,
            "--fontstroke": stroke.style.fontFamily,
          } as CSSProperties
        }
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
